export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const SORT_COLUMN = 'SORT_COLUMN';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const SEARCH_DISTRICT_VALUE = 'SEARCH_DISTRICT_VALUE';

export const FETCH_DISTRICT_REQUEST = 'FETCH_DISTRICT_REQUEST';
export const FETCH_DISTRICT_SUCCESS = 'FETCH_DISTRICT_SUCCESS';
export const FETCH_DISTRICT_FAILURE = 'FETCH_DISTRICT_FAILURE';

export const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
export const LOAD_EXACT_PAGE = "LOAD_EXACT_PAGE";